version: "3"

services:
  flask:
    build:
      context: flask
    ports:
      - "5000:5000"
    links:
      - django
  django:
    build:
      context: nlp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db 
  db:
    image: "postgres"
    container_name: "localpg"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes: 
  postgresql-volume:
    external: true